### ISSUE TITLE
[Crash] Incompatible with Mythic Metals?

### ISSUE THREAD

**Issue by Kelsey83514** [SuperMartijn642/OreGrowth#5]
**Version Info**
- Minecraft, 1.20.1
- Ore Growth, 1.0.4

**What mod loader are you using?**: Fabric

**Steps to Reproduce**
Create a new modpack on 1.20.1 Fabric, then add both Ore Growth and Mythic Metals (as well as their dependencies)
Load up Minecraft, and try to create a new world. It immediately crashes from there

**Crash report (~/logs/latest.log)**
Please see attached
[latest.log](https://github.com/SuperMartijn642/OreGrowth/files/13060823/latest.log)

**Comment by SuperMartijn642** [comment]
For me the game just shows the datapack warning screen though:
![image](https://github.com/SuperMartijn642/OreGrowth/assets/12382965/84312dae-76b2-451d-b3c7-90598aeaa25d)
Does your game actually crash or does it show that screen? If it actually crashes, that might be caused by some other mod you have installed.

Seems I made some mistakes in the ore growth recipes for ores from Mythic Metals. I have fixed those now in Ore Growth version 1.0.5.

**Comment by Kelsey83514** [comment]
The game immediately crashed as soon as I clicked on 'Singleplayer', so I didn't even have the option to create a world, and I don't think it could have been any other mod - the only ones I had in the test pack were Ore Growth, Mythic Metals, and their dependencies. Not sure why we got different results. Anyway, I tried with the new version and it works. Thanks for fixing it so quickly!
